const path = require('path');

module.exports = {
  apps: [
    {
      name: 'odin-backend',
      script: './backend/dist/server.js',
      cwd: path.resolve(__dirname),
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        DATABASE_URL: 'postgresql://odin:odin_2026_secure@localhost:5432/odin_observer',
        SESSION_SECRET: 'odin_session_secret_2026_innovadataco',
        JWT_SECRET: 'odin_jwt_secret_2026_innovadataco',
        GOOGLE_CLIENT_ID: 'YOUR_GOOGLE_CLIENT_ID_HERE',
        GOOGLE_CLIENT_SECRET: 'YOUR_GOOGLE_CLIENT_SECRET_HERE',
        GOOGLE_CALLBACK_URL: 'http://YOUR_SERVER_IP:3000/api/auth/google/callback',
      },
      env_production: {
        NODE_ENV: 'production',
      },
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '512M',
      restart_delay: 3000,
      log_file: './logs/backend-combined.log',
      out_file: './logs/backend-out.log',
      error_file: './logs/backend-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      kill_timeout: 5000,
      listen_timeout: 8000,
      wait_ready: true,
    },
    {
      name: 'odin-frontend',
      script: './serve-frontend.js',
      cwd: path.resolve(__dirname),
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
      },
      env_production: {
        NODE_ENV: 'production',
      },
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '256M',
      restart_delay: 3000,
      log_file: './logs/frontend-combined.log',
      out_file: './logs/frontend-out.log',
      error_file: './logs/frontend-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      kill_timeout: 5000,
    },
  ],
};